### ISSUE TITLE
16. Meeting Software Lab - Report

### ISSUE THREAD

**Issue by ga45fat** [ga45fat/vtu11#24]
**Discussed Topics:**

- How to structure the second presentation best
- some remarks about the already included parts in the presentation
        1. Add distributed vs shared memory parallelism to the presentation (also compare MPI with OpenMP in this section)
        2. A thread is a logical part of a process, which is the software part and CPU is a mechanical part
        3. Kratos is doing a finite element partitioning, so the partitioning is always correct, it can only happen, that the number of 
            cells per chunk is unbalanced
        4. Call Kratos "Kratos Multiphysics"
        5. think about the input parameter "fileId" for the write_PVTU function
- We tried different options for running the vtu11 library within Kratos in parallel
      -->Encountered error: crashes at some point, because folder is created, while another process checks, if it exists. So at some 
            point, it might happen, that the folder is created twice, which causes an error 
                --> Possible solution: use MPI_Barrier(Communicator) to synchronise all processes
                --> Other solution: make sure, all directories are created correctly beforehand

**Tasks:** 

- [ ] finish the slides and the recording for the second presentation
- [ ] somehow try to get Kratos running so that a timechecking can be done
- [ ] create different simulation examples for visualizing the partitioning

Next meeting: as soon as Philipp B. returns from holiday ;-) (Maybe on Monday 9.11.)
